# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/14c9c963-34bd-4f1f-bc6b-458e277050a6";
      fsType = "btrfs";
      options = [ "subvol=@nixos" "compress=zstd:1" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/14c9c963-34bd-4f1f-bc6b-458e277050a6";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:1" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4C24-0AA6";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
