#!/usr/bin/env bash
NVIM_SOCKET="$HOME/.cache/nvim.sock"
# [ "$#" -gt 0 ] && set -- $(realpath -- "$@")
if [ "$#" -gt 0 ]; then
    mapfile -t real_files < <(realpath -- "$@")
    set -- "${real_files[@]}"
fi
if n_=$(nvim --headless --server "$NVIM_SOCKET" --remote-expr "1" 2>/dev/null); then
if [ "$#" -eq 0 ]; then set -- "unnamed"; fi
  exec nvim --server "$NVIM_SOCKET" --remote "$@"
else
  rm -f $NVIM_SOCKET
  exec nvim --listen "$NVIM_SOCKET" "$@"
fi
